<?php
/**
 * VerySimpleDownload.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package VerySimpleDownload
 * @author Ralf Koester <ralf@zikula.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Upload handler implementation class.
 */
class VerySimpleDownload_UploadHandler extends VerySimpleDownload_Base_UploadHandler
{
    // feel free to add your upload handler enhancements here
    public function __construct()
    {	
		parent::__construct();
		$this->allowedFileSizes['download'] = ModUtil::getVar('VerySimpleDownload', 'myFileSize', 102400);
	}
	
	    protected function isAllowedFileExtension($objectType, $fieldName, $extension)
    {
        // determine the allowed extensions
        $allowedExtensions = array();
        switch ($objectType) {
            case 'download':
                 $allowedExtensions = explode(', ', ModUtil::getVar('VerySimpleDownload', 'myFileExtensions'));
                    break;
        }
    
        if (count($allowedExtensions) > 0) {
            if (!in_array($extension, $allowedExtensions)) {
                return false;
            }
        }
    
        if (in_array($extension, $this->forbiddenFileTypes)) {
            return false;
        }
    
        return true;
    }
}
