<?php
/**
 * VerySimpleDownload.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package VerySimpleDownload
 * @author Ralf Koester <ralf@zikula.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de) at Mon Jan 20 19:00:40 CET 2014.
 */

/**
 * Version information implementation class.
 */
class VerySimpleDownload_Version extends VerySimpleDownload_Base_Version
{
    // custom enhancements can go here
}
