<?php
/**
 * VerySimpleDownload.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package VerySimpleDownload
 * @author Ralf Koester <ralf@zikula.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * This handler class handles the page events of the Form called by the verySimpleDownload_user_edit() function.
 * It aims on the download object type.
 */
class VerySimpleDownload_Form_Handler_User_Download_Edit extends VerySimpleDownload_Form_Handler_User_Download_Base_Edit
{
    // feel free to extend the base handler class here
}
