<?php
/**
 * Simpledownload.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Simpledownload
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de) at Tue Jan 14 18:08:53 CET 2014.
 */

/**
 * Version information implementation class.
 */
class Simpledownload_Version extends Simpledownload_Base_Version
{
    // custom enhancements can go here
}
