<?php
/**
 * Simpledownload.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Simpledownload
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing download categories.
 *
 * This is the concrete category class for download entities.
* @ORM\Entity(repositoryClass="Simpledownload_Entity_Repository_DownloadCategory")
   * @ORM\Table(name="simdown_download_category",
   *     uniqueConstraints={
   *         @ORM\UniqueConstraint(name="cat_unq", columns={"registryId", "categoryId", "entityId"})
   *     }
   * )
 */
class Simpledownload_Entity_DownloadCategory extends Simpledownload_Entity_Base_DownloadCategory
{
    // feel free to add your own methods here
}
