<?php
/**
 * VerySimpleDownload.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package VerySimpleDownload
 * @author Ralf Koester <ralf@zikula.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * This is the Ajax controller class providing navigation and interaction functionality.
 */
class VerySimpleDownload_Controller_Ajax extends VerySimpleDownload_Controller_Base_Ajax
{
    // feel free to add your own controller methods here
}
