<?php
/**
 * Simpledownload.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Simpledownload
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing download categories.
 *
 * This is the base category class for download entities.
 */
class Simpledownload_Entity_Base_DownloadCategory extends Zikula_Doctrine2_Entity_EntityCategory
{
    /**
     * @ORM\ManyToOne(targetEntity="Simpledownload_Entity_Download", inversedBy="categories")
     * @ORM\JoinColumn(name="entityId", referencedColumnName="id")
     * @var Simpledownload_Entity_Download
     */
    protected $entity;

    /**
     * Get reference to owning entity.
     *
     * @return Simpledownload_Entity_Download
     */
    public function getEntity()
    {
        return $this->entity;
    }

    /**
     * Set reference to owning entity.
     *
     * @param Simpledownload_Entity_Download $entity
     */
    public function setEntity(/*Simpledownload_Entity_Download */$entity)
    {
        $this->entity = $entity;
    }
}
