<?php
/**
 * VerySimpleDownload.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package VerySimpleDownload
 * @author Ralf Koester <ralf@zikula.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Item selector plugin implementation class.
 */
class VerySimpleDownload_Form_Plugin_ItemSelector extends VerySimpleDownload_Form_Plugin_Base_ItemSelector
{
    // feel free to add your customisation here
}
