<?php
/**
 * Simpledownload.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Simpledownload
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Installer base class.
 */
class Simpledownload_Base_Installer extends Zikula_AbstractInstaller
{
    /**
     * Install the Simpledownload application.
     *
     * @return boolean True on success, or false.
     */
    public function install()
    {
        // Check if upload directories exist and if needed create them
        try {
            $controllerHelper = new Simpledownload_Util_Controller($this->serviceManager);
            $controllerHelper->checkAndCreateAllUploadFolders();
        } catch (\Exception $e) {
            return LogUtil::registerError($e->getMessage());
        }
        // create all tables from according entity definitions
        try {
            DoctrineHelper::createSchema($this->entityManager, $this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            $returnMessage = $this->__f('An error was encountered while creating the tables for the %s extension.', array($this->name));
            if (!System::isDevelopmentMode()) {
                $returnMessage .= ' ' . $this->__('Please enable the development mode by editing the /config/config.php file in order to reveal the error details.');
            }
            return LogUtil::registerError($returnMessage);
        }
    
        $categoryRegistryIdsPerEntity = array();
    
        // add default entry for category registry (property named Main)
        include_once 'modules/Simpledownload/lib/Simpledownload/Api/Base/Category.php';
        include_once 'modules/Simpledownload/lib/Simpledownload/Api/Category.php';
        $categoryApi = new Simpledownload_Api_Category($this->serviceManager);
    
        $registryData = array();
        $registryData['modname'] = $this->name;
        $registryData['table'] = 'Download';
        $registryData['property'] = $categoryApi->getPrimaryProperty(array('ot' => 'Download'));
        $categoryGlobal = CategoryUtil::getCategoryByPath('/__SYSTEM__/Modules/Global');
        $registryData['category_id'] = $categoryGlobal['id'];
        $registryData['id'] = false;
        if (!DBUtil::insertObject($registryData, 'categories_registry')) {
            LogUtil::registerError($this->__f('Error! Could not create a category registry for the %s entity.', array('download')));
        }
        $categoryRegistryIdsPerEntity['download'] = $registryData['id'];
    
        // create the default data
        $this->createDefaultData($categoryRegistryIdsPerEntity);
    
        // register persistent event handlers
        $this->registerPersistentEventHandlers();
    
        // register hook subscriber bundles
        HookUtil::registerSubscriberBundles($this->version->getHookSubscriberBundles());
        
    
        // initialisation successful
        return true;
    }
    
    /**
     * Upgrade the Simpledownload application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldVersion Version to upgrade from.
     *
     * @return boolean True on success, false otherwise.
     */
    public function upgrade($oldVersion)
    {
    /*
        // Upgrade dependent on old version number
        switch ($oldVersion) {
            case 1.0.0:
                // do something
                // ...
                // update the database schema
                try {
                    DoctrineHelper::updateSchema($this->entityManager, $this->listEntityClasses());
                } catch (\Exception $e) {
                    if (System::isDevelopmentMode()) {
                        LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
                    }
                    return LogUtil::registerError($this->__f('An error was encountered while updating tables for the %s extension.', array($this->getName())));
                }
        }
    */
    
        // update successful
        return true;
    }
    
    /**
     * Uninstall Simpledownload.
     *
     * @return boolean True on success, false otherwise.
     */
    public function uninstall()
    {
        // delete stored object workflows
        $result = Zikula_Workflow_Util::deleteWorkflowsForModule($this->getName());
        if ($result === false) {
            return LogUtil::registerError($this->__f('An error was encountered while removing stored object workflows for the %s extension.', array($this->getName())));
        }
    
        try {
            DoctrineHelper::dropSchema($this->entityManager, $this->listEntityClasses());
        } catch (\Exception $e) {
            if (System::isDevelopmentMode()) {
                LogUtil::registerError($this->__('Doctrine Exception: ') . $e->getMessage());
            }
            return LogUtil::registerError($this->__f('An error was encountered while dropping tables for the %s extension.', array($this->name)));
        }
    
        // unregister persistent event handlers
        EventUtil::unregisterPersistentModuleHandlers($this->name);
    
        // unregister hook subscriber bundles
        HookUtil::unregisterSubscriberBundles($this->version->getHookSubscriberBundles());
        
    
        // remove category registry entries
        ModUtil::dbInfoLoad('Categories');
        DBUtil::deleteWhere('categories_registry', 'modname = \'' . $this->name . '\'');
    
        // remove all thumbnails
        $manager = $this->getServiceManager()->getService('systemplugin.imagine.manager');
        $manager->setModule($this->name);
        $manager->cleanupModuleThumbs();
    
        // remind user about upload folders not being deleted
        $uploadPath = FileUtil::getDataDirectory() . '/' . $this->name . '/';
        LogUtil::registerStatus($this->__f('The upload directories at [%s] can be removed manually.', $uploadPath));
    
        // uninstallation successful
        return true;
    }
    
    /**
     * Build array with all entity classes for Simpledownload.
     *
     * @return array list of class names.
     */
    protected function listEntityClasses()
    {
        $classNames = array();
        $classNames[] = 'Simpledownload_Entity_Download';
        $classNames[] = 'Simpledownload_Entity_DownloadCategory';
    
        return $classNames;
    }
    
    /**
     * Create the default data for Simpledownload.
     *
     * @param array $categoryRegistryIdsPerEntity List of category registry ids.
     *
     * @return void
     */
    protected function createDefaultData($categoryRegistryIdsPerEntity)
    {
        $entityClass = 'Simpledownload_Entity_Download';
        $this->entityManager->getRepository($entityClass)->truncateTable();
    }
    
    /**
     * Register persistent event handlers.
     * These are listeners for external events of the core and other modules.
     */
    protected function registerPersistentEventHandlers()
    {
        // core -> 
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'api.method_not_found', array('Simpledownload_Listener_Core', 'apiMethodNotFound'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'core.preinit', array('Simpledownload_Listener_Core', 'preInit'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'core.init', array('Simpledownload_Listener_Core', 'init'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'core.postinit', array('Simpledownload_Listener_Core', 'postInit'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'controller.method_not_found', array('Simpledownload_Listener_Core', 'controllerMethodNotFound'));
    
        // front controller -> Simpledownload_Listener_FrontController
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'frontcontroller.predispatch', array('Simpledownload_Listener_FrontController', 'preDispatch'));
    
        // installer -> Simpledownload_Listener_Installer
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'installer.module.installed', array('Simpledownload_Listener_Installer', 'moduleInstalled'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'installer.module.upgraded', array('Simpledownload_Listener_Installer', 'moduleUpgraded'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'installer.module.uninstalled', array('Simpledownload_Listener_Installer', 'moduleUninstalled'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'installer.subscriberarea.uninstalled', array('Simpledownload_Listener_Installer', 'subscriberAreaUninstalled'));
    
        // modules -> Simpledownload_Listener_ModuleDispatch
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'module_dispatch.postloadgeneric', array('Simpledownload_Listener_ModuleDispatch', 'postLoadGeneric'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'module_dispatch.preexecute', array('Simpledownload_Listener_ModuleDispatch', 'preExecute'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'module_dispatch.postexecute', array('Simpledownload_Listener_ModuleDispatch', 'postExecute'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'module_dispatch.custom_classname', array('Simpledownload_Listener_ModuleDispatch', 'customClassname'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'module_dispatch.service_links', array('Simpledownload_Listener_ModuleDispatch', 'serviceLinks'));
    
        // mailer -> Simpledownload_Listener_Mailer
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'module.mailer.api.sendmessage', array('Simpledownload_Listener_Mailer', 'sendMessage'));
    
        // page -> Simpledownload_Listener_Page
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'pageutil.addvar_filter', array('Simpledownload_Listener_Page', 'pageutilAddvarFilter'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'system.outputfilter', array('Simpledownload_Listener_Page', 'systemOutputfilter'));
    
        // errors -> Simpledownload_Listener_Errors
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'setup.errorreporting', array('Simpledownload_Listener_Errors', 'setupErrorReporting'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'systemerror', array('Simpledownload_Listener_Errors', 'systemError'));
    
        // theme -> Simpledownload_Listener_Theme
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'theme.preinit', array('Simpledownload_Listener_Theme', 'preInit'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'theme.init', array('Simpledownload_Listener_Theme', 'init'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'theme.load_config', array('Simpledownload_Listener_Theme', 'loadConfig'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'theme.prefetch', array('Simpledownload_Listener_Theme', 'preFetch'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'theme.postfetch', array('Simpledownload_Listener_Theme', 'postFetch'));
    
        // view -> Simpledownload_Listener_View
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'view.init', array('Simpledownload_Listener_View', 'init'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'view.postfetch', array('Simpledownload_Listener_View', 'postFetch'));
    
        // user login -> Simpledownload_Listener_UserLogin
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'module.users.ui.login.started', array('Simpledownload_Listener_UserLogin', 'started'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'module.users.ui.login.veto', array('Simpledownload_Listener_UserLogin', 'veto'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'module.users.ui.login.succeeded', array('Simpledownload_Listener_UserLogin', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'module.users.ui.login.failed', array('Simpledownload_Listener_UserLogin', 'failed'));
    
        // user logout -> Simpledownload_Listener_UserLogout
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'module.users.ui.logout.succeeded', array('Simpledownload_Listener_UserLogout', 'succeeded'));
    
        // user -> Simpledownload_Listener_User
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'user.gettheme', array('Simpledownload_Listener_User', 'getTheme'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'user.account.create', array('Simpledownload_Listener_User', 'create'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'user.account.update', array('Simpledownload_Listener_User', 'update'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'user.account.delete', array('Simpledownload_Listener_User', 'delete'));
    
        // registration -> Simpledownload_Listener_UserRegistration
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'module.users.ui.registration.started', array('Simpledownload_Listener_UserRegistration', 'started'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'module.users.ui.registration.succeeded', array('Simpledownload_Listener_UserRegistration', 'succeeded'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'module.users.ui.registration.failed', array('Simpledownload_Listener_UserRegistration', 'failed'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'user.registration.create', array('Simpledownload_Listener_UserRegistration', 'create'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'user.registration.update', array('Simpledownload_Listener_UserRegistration', 'update'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'user.registration.delete', array('Simpledownload_Listener_UserRegistration', 'delete'));
    
        // users module -> Simpledownload_Listener_Users
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'module.users.config.updated', array('Simpledownload_Listener_Users', 'configUpdated'));
    
        // group -> Simpledownload_Listener_Group
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'group.create', array('Simpledownload_Listener_Group', 'create'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'group.update', array('Simpledownload_Listener_Group', 'update'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'group.delete', array('Simpledownload_Listener_Group', 'delete'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'group.adduser', array('Simpledownload_Listener_Group', 'addUser'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'group.removeuser', array('Simpledownload_Listener_Group', 'removeUser'));
    
        // special purposes and 3rd party api support -> Simpledownload_Listener_ThirdParty
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'get.pending_content', array('Simpledownload_Listener_ThirdParty', 'pendingContentListener'));
        EventUtil::registerPersistentModuleHandler('Simpledownload', 'module.content.gettypes', array('Simpledownload_Listener_ThirdParty', 'contentGetTypes'));
    }
}
