<?php
/**
 * Simpledownload.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Simpledownload
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de) at Sun Dec 29 13:08:41 CET 2013.
 */

/**
 * Version information base class.
 */
class Simpledownload_Base_Version extends Zikula_AbstractVersion
{
    /**
     * Retrieves meta data information for this application.
     *
     * @return array List of meta data.
     */
    public function getMetaData()
    {
        $meta = array();
        // the current module version
        $meta['version']              = '0.0.1';
        // the displayed name of the module
        $meta['displayname']          = $this->__('Simpledownload');
        // the module description
        $meta['description']          = $this->__('a module for simple download');
        //! url version of name, should be in lowercase without space
        $meta['url']                  = $this->__('simpledownload');
        // core requirement
        $meta['core_min']             = '1.3.5'; // requires minimum 1.3.5
        $meta['core_max']             = '1.3.6'; // not ready for 1.3.7 yet

        // define special capabilities of this module
        $meta['capabilities'] = array(
                          HookUtil::SUBSCRIBER_CAPABLE => array('enabled' => true)
/*,
                          HookUtil::PROVIDER_CAPABLE => array('enabled' => true), // TODO: see #15
                          'authentication' => array('version' => '1.0'),
                          'profile'        => array('version' => '1.0', 'anotherkey' => 'anothervalue'),
                          'message'        => array('version' => '1.0', 'anotherkey' => 'anothervalue')
*/
        );

        // permission schema
        $meta['securityschema'] = array(
            'Simpledownload::' => '::',
            'Simpledownload::Ajax' => '::',
            'Simpledownload:ItemListBlock:' => 'Block title::',
            'Simpledownload:Download:' => 'Download ID::',
        );
        // DEBUG: permission schema aspect ends


        return $meta;
    }

    /**
     * Define hook subscriber bundles.
     */
    protected function setupHookBundles()
    {
        
        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.simpledownload.ui_hooks.downloads', 'ui_hooks', __('simpledownload Downloads Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'simpledownload.ui_hooks.downloads.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'simpledownload.ui_hooks.downloads.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'simpledownload.ui_hooks.downloads.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'simpledownload.ui_hooks.downloads.validate_edit');
        // Validate input from an ui create/edit form (generally not used).
        $bundle->addEvent('validate_delete', 'simpledownload.ui_hooks.downloads.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'simpledownload.ui_hooks.downloads.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'simpledownload.ui_hooks.downloads.process_delete');
        $this->registerHookSubscriberBundle($bundle);

        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.simpledownload.filter_hooks.downloads', 'filter_hooks', __('simpledownload Downloads Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'simpledownload.filter_hooks.downloads.filter');
        $this->registerHookSubscriberBundle($bundle);

        
    }
}
