<?php
/**
 * Simpledownload.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Simpledownload
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * This handler class handles the page events of the Form called by the simpledownload_admin_edit() function.
 * It collects common functionality required by different object types.
 */
class Simpledownload_Form_Handler_Admin_Edit extends Simpledownload_Form_Handler_Admin_Base_Edit
{
    // feel free to extend the base handler class here
}
