<?php
/**
 * VerySimpleDownload.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package VerySimpleDownload
 * @author Ralf Koester <ralf@zikula.de>.
 * @link http://support.zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Permission check for workflow schema 'standard'.
 * This function allows to calculate complex permission checks.
 * It receives the object the workflow engine is being asked to process and the permission level the action requires.
 *
 * @param array  $obj         The currently treated object.
 * @param int    $permLevel   The required workflow permission level.
 * @param int    $currentUser Id of current user.
 * @param string $actionId    Id of the workflow action to be executed.
 *
 * @return bool Whether the current user is allowed to execute the action or not.
 */
function VerySimpleDownload_workflow_standard_permissioncheck($obj, $permLevel, $currentUser, $actionId)
{
    // calculate the permission component
    $objectType = $obj['_objectType'];
    $component = 'VerySimpleDownload:' . ucwords($objectType) . ':';

    // calculate the permission instance
    $idFields = ModUtil::apiFunc('VerySimpleDownload', 'selection', 'getIdFields', array('ot' => $objectType));
    $instanceId = '';
    foreach ($idFields as $idField) {
        if (!empty($instanceId)) {
            $instanceId .= '_';
        }
        $instanceId .= $obj[$idField];
    }
    $instance = $instanceId . '::';

    // now perform the permission check
    $result = SecurityUtil::checkPermission($component, $instance, $permLevel, $currentUser);

    // check whether the current user is the owner
    if (!$result && isset($obj['createdUserId']) && $obj['createdUserId'] == $currentUser) {
        // allow author update operations for all states which occur before 'approved' in the object's life cycle.
        $result = in_array($actionId, array('initial', 'deferred', 'waiting', 'accepted'));
    }

    return $result;
}

/**
 * This helper functions cares for including the strings used in the workflow into translation.
 */
function VerySimpleDownload_workflow_standard_gettextstrings()
{
    return array(
        'title' => no__('Standard workflow (single approval)'),
        'description' => no__('This is a two staged workflow with stages for untrusted submissions and finally approved publications. It does not allow corrections of non-editors to published pages.'),

        // state titles
        'states' => array(
            no__('Initial') => no__('Pseudo-state for content which is just created and not persisted yet.'),
            no__('Deferred') => no__('Content has not been submitted yet or has been waiting, but was rejected.'),
            no__('Waiting') => no__('Content has been submitted and waits for approval.'),
            no__('Approved') => no__('Content has been approved and is available online.'),
            no__('Deleted') => no__('Pseudo-state for content which has been deleted from the database.')
        ),

        // action titles and descriptions for each state
        'actions' => array(
            'initial' => array(
                no__('Submit') => no__('Submit content for acceptance by a moderator.'),
                no__('Submit and Approve') => no__('Submit content and approve immediately.'),
                no__('Defer') => no__('Defer content for later submission.'),
            )
            ,
            'deferred' => array(
                no__('Submit') => no__('Submit content for acceptance by a moderator.'),
                no__('Update') => no__('Update content.'),
                no__('Delete') => no__('Delete content permanently.')
            )
            ,
            'waiting' => array(
                no__('Update') => no__('Update content.'),
                no__('Reject') => no__('Reject content and require improvements.'),
                no__('Approve') => no__('Update content and approve for immediate publishing.'),
                no__('Delete') => no__('Delete content permanently.')
            )
            ,
            'approved' => array(
                no__('Update') => no__('Update content.'),
                no__('Delete') => no__('Delete content permanently.')
            )
            ,
            'deleted' => array(
            )
        )
    );
}
