<?php
/**
 * Simpledownload.
 *
 * @copyright Ralf Koester (Koester)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Simpledownload
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Item selector plugin implementation class.
 */
class Simpledownload_Form_Plugin_ItemSelector extends Simpledownload_Form_Plugin_Base_ItemSelector
{
    // feel free to add your customisation here
}
